# Generated by Django 3.2.3 on 2021-05-15 08:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_api', '0002_auto_20210515_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
