# Generated by Django 3.2.3 on 2021-05-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_api', '0003_podcast_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
