# Generated by Django 3.2.3 on 2021-05-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_api', '0004_alter_podcast_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='options',
        ),
    ]
